- hosts: localhost
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-image
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance
