- hosts: ccc-db
  gather_facts: true
  vars_files:
    - host_vars/couchdb.yaml
  vars:
    master_node: "db4"
    nodes: ["db4", "db5"]
    ports: [5984, 15984, 25984]
    couchdb_user: admin
    couchdb_pass: admin
    size: "{{ groups['ccc-db'] | length }}"


  tasks:
    - name: Enable cluster setup
      uri:
        url: "http://{{ couchdb_user }}:{{ couchdb_pass }}@{{ hostvars[item]['ansible_host'] }}:5984/_cluster_setup"
        method: POST
        body_format: json
        body:
          action: enable_cluster
          bind_address: "0.0.0.0"
          username: "{{ couchdb_user }}"
          password: "{{ couchdb_pass }}"
          node_count: "{{ size }}"
        status_code: 200
      loop: "{{ nodes }}"
      when: inventory_hostname == item

    - name: Add nodes to cluster
      uri:
        url: "http://{{ couchdb_user }}:{{ couchdb_pass }}@{{ hostvars[master_node]['ansible_host'] }}:5984/_cluster_setup"
        method: POST
        body_format: json
        body:
          action: "add_node"
          host: "{{ hostvars[item]['ansible_host'] }}"
          port: 5984
          username: "{{ couchdb_user }}"
          password: "{{ couchdb_pass }}"
        status_code: 200
      loop: "{{ nodes }}"
      when: inventory_hostname == item and item != master_node

    - name: Finish cluster setup
      uri:
        url: "http://{{ couchdb_user }}:{{ couchdb_pass }}@{{ groups[master_node][0] }}:5984/_cluster_setup"
        method: POST
        body_format: json
        body:
          action: "finish_cluster"
        status_code: 200
      run_once: true
      when: inventory_hostname == master_node

    - name: Check cluster status
      uri:
        url: "http://{{ couchdb_user }}:{{ couchdb_pass }}@{{ groups[master_node][0] }}:5984/_membership"
        method: GET
        return_content: yes
      register: cluster_status
      when: inventory_hostname == master_node

    - name: Display cluster status
      debug:
        var: cluster_status.content
      when: inventory_hostname == master_node
