import "server-only";

import { copyFileSync, existsSync } from "node:fs";
import path from "node:path";
import { createClient, type Client, type InValue } from "@libsql/client";

/**
 * Read-only analytics database (web/data/analytics.db), generated by
 * scripts/build_analytics.py. It is bundled with the server output via
 * `outputFileTracingIncludes` in next.config.ts.
 */
const SOURCE = path.join(process.cwd(), "data", "analytics.db");

let client: Client | null = null;

function resolveFile(): string {
  // Serverless file systems are read-only outside /tmp; SQLite only needs
  // read access, but copying once per cold start avoids any journal or lock
  // surprises and costs ~2 ms for a 1.7 MB file.
  if (process.env.VERCEL) {
    const tmp = "/tmp/social-sense-analytics.db";
    if (!existsSync(tmp)) copyFileSync(SOURCE, tmp);
    return tmp;
  }
  return SOURCE;
}

export function db(): Client {
  client ??= createClient({ url: `file:${resolveFile()}` });
  return client;
}

/** Run a read-only query and return plain objects. */
export async function query<T>(sql: string, args: InValue[] = []): Promise<T[]> {
  if (!/^\s*(select|with|pragma)\b/i.test(sql)) throw new Error("analytics.db is read-only");
  const rs = await db().execute({ sql, args });
  return rs.rows.map((row) => {
    const o: Record<string, unknown> = {};
    for (const c of rs.columns) o[c] = row[c] ?? null;
    return o as T;
  });
}
