---

- name: Create a volumn
  openstack.cloud.volume:
    availability_zone: '{{ availability_zone }}'
    display_name: '{{ item.vol_name }}'
    size: '{{ item.vol_size }}'
    timeout: 600
    state: present
  loop: '{{ volumes }}'
  register: os_vol

- name: print return information from the previous task
  ansible.builtin.debug:
    var: os_vol

- name: Create a list of volume Ids
  ansible.builtin.set_fact:
    os_vol_ids: '{{ os_vol_ids | default([]) + [item.volume.id] }}'
  loop: '{{ os_vol.results }}'

- ansible.builtin.debug:
    msg: "volume {{ os_vol_ids }} has been created"
