---
- name: Deploy React application to MRC Unimelb Cloud server
  user: name="ubuntu" shell="/usr/local/bin/fish"
  hosts: ccc-frontend
  become: yes
  vars:
    react_app_name: reactapp
    react_app_directory: /home/ubuntu/{{ react_app_name }}
    react_app_repo: git@github.com:rNLKJA/Unimelb-Master-2023-COMP90024-Assignment-2.git
  tasks:
    - name: Install required packages
      apt:
        name:
          - git
          - nodejs
          - npm
          - docker.io
        state: present
        update_cache: yes
    - name: Add GitHub's host key to known hosts
      ansible.builtin.known_hosts:
        name: github.com
        key: "{{ lookup('pipe', 'ssh-keyscan github.com') }}"
        state: present
    
    - name: Copy the private SSH key to the target server
      ansible.builtin.copy:
        ## copy the private SSH key of github to the target server
        ## replay the path with your own private key path
        src: /Users/weizhao1/.ssh/id_ed25519
        dest: /home/ubuntu/.ssh/cloud_backend.key
        owner: ubuntu
        group: ubuntu
        mode: '0600'
    
    - name: add git config
      ansible.builtin.shell: |
        git config --global --add safe.directory /home/ubuntu/{{react_app_name}}


    - name: Clone the React application repository
      become: yes
      git:
        repo: git@github.com:rNLKJA/Unimelb-Master-2023-COMP90024-Assignment-2.git
        dest: "{{ react_app_directory }}"
        version: 2-frontend
        update: yes
      environment:
        GIT_SSH_COMMAND: "ssh -i /home/ubuntu/.ssh/cloud_backend.key -o StrictHostKeyChecking=no"


    - name: Build the docker image
      docker_image:
        name: reactapp:latest
        source: build
        build:
          path: "{{react_app_directory}}/2_ReactJS_frontend/frontend"
        state: present


    - name: Run the docker container
      docker_container:
        name: reactapp
        image: reactapp:latest
        state: started
        ports:
          - "80:80"

        restart_policy: always