---
- name: Deploy Flask application to MRC Unimelb Cloud server
  user: name="ubuntu" shell="/usr/local/bin/fish"
  hosts: 172.26.128.118
  become: yes
  vars:
    flask_app_name: my_flask_app
    flask_app_directory: /home/ubuntu/{{ flask_app_name }}
    flask_app_repo: git@github.com:rNLKJA/Unimelb-Master-2023-COMP90024-Assignment-2.git
    virtualenv_directory: "{{flask_app_directory}}/flask-backend/venv"
  tasks:
    - name: Install required packages
      apt:
        name:
          - python3-pip
          - python3-venv
          - python3-flask
          - git
          - nginx
          - supervisor
          - python3-virtualenv
          - gunicorn
          - docker.io
        state: present
        update_cache: yes
    - name: Add GitHub's host key to known hosts
      ansible.builtin.known_hosts:
        name: github.com
        key: "{{ lookup('pipe', 'ssh-keyscan github.com') }}"
        state: present
    
    - name: Copy the private SSH key to the target server
      ansible.builtin.copy:
        ## copy the private SSH key of github to the target server
        ## replay the path with your own private key path
        src: /Users/weizhao1/.ssh/id_ed25519
        dest: /home/ubuntu/.ssh/cloud_backend.key
        owner: ubuntu
        group: ubuntu
        mode: '0600'


    - name: Clone the Flask application repository
      git:
        repo: git@github.com:rNLKJA/Unimelb-Master-2023-COMP90024-Assignment-2.git
        dest: "{{ flask_app_directory }}"
        version: 1-backend
        update: yes
      environment:
        GIT_SSH_COMMAND: "ssh -i /home/ubuntu/.ssh/cloud_backend.key -o StrictHostKeyChecking=no"

    # - name: Manually create the initial virtualenv
    #   command:
    #     cmd: python3 -m venv {{flask_app_directory}}/flask-backend/venv
    #     creates: "{{flask_app_directory}}/flask-backend/venv"   

    - name: Build the docker image
      docker_image:
        name: flask-backend:1.0
        source: build
        build:
          path: "{{flask_app_directory}}/flask-backend"
        state: present


    - name: Run the docker container
      docker_container:
        name: flask-backend
        image: flask-backend:1.0
        state: started
        ports:
          - "8000:8080"

        restart_policy: always

    - name: config nginx
      template:

        ## replace the config path to your own config path
        src:  /Users/weizhao1/Documents/Unimelb-Master-2023-COMP90024-Assignment-2/server_deployment/ansible/roles/flask-backend/templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/flask

    - name: Enable nginx site
      file:
        src: /etc/nginx/sites-available/flask
        dest: /etc/nginx/sites-enabled/flask
        state: link
      notify:
        - restart nginx

  handlers:

    - name: restart nginx
      service:
        name: nginx
        state: restarted

    # - name: Install requirements
    #   ansible.builtin.pip: 
    #     requirements=/{{flask_app_directory}}/requirements.txt 

    # - name: Activate dependencies
    #   ansible.builtin.shell: 
    #     cmd: source /home/ubuntu/my_flask_app/flask-backend/venv/bin/activate
    #   args:
    #     executable: /bin/bash

    # - name: Deploy the flask app on port 8080

    #   ansible.builtin.shell: 
    #     cmd: cd {{flask_app_directory}}/flask-backend/ && screen gunicorn --bind 0.0.0.0:8080 wsgi:app


    ## TODO: config the nginx and run the flask app on port 8080

    # - name: Run the flask app on port 8080
    #   command: cd ~/my_flask_app/flask-backend/
    #   command: flask run --host 0.0.0.0 --port 8080


